### PR TITLE
Took care of null errors

### PR DESCRIPTION
**Pull request by SupremeDeity**
While i have took care of null errors, i still do get:
`Bad state: No record found for [https://oauth.reddit.com/r/drawapitesting/comments/, {limit: 10}].`

Does this need to be fixed?

Also i would recommend the merge process to be:
1st) Merge #205 
2nd) Merge this one. This should merge and give credit to both me and @brianrobles204.

### CODE REVIEW

**Comment by brianrobles204** [comment]
Hello, I tested this branch and I get the same error when running the test. 

The problem is with the json recording, because the request field is outdated now. I think the simplest solution is to edit `test/subreddit/lib_subreddit_comments_stream.json` and `test/subreddit/lib_subreddits_stream.json` to remove the `before` entry in the request params field. I pushed a branch with these changes to my fork [here](https://github.com/brianrobles204/DRAW/tree/null-safe-json-fix), you can merge to this PR if you like. OR we could rerun the failing tests in live mode and write the new recordings, do we need `/u/DRAWApiOfficial`'s access to do this?

I can verify that once the json recordings are updated, all tests pass in sound null-safety mode :)

**Comment by SupremeDeity** [comment]
> do we need /u/DRAWApiOfficial's access to do this?

Yes we need access to `u/DrawApiOfficial` for this.

Since the updated recording just work i would be okay with just merging it, however i am waiting for @bkonyi on what he wants to do.

**Comment by bkonyi** [comment]
Yes, that test will need to be fixed. I've gone ahead and done that and merged it into master.

**Comment by SupremeDeity** [comment]
Since this is taken care, this should be okay for merge right? Or is there something still remaining.

**Comment by SupremeDeity** [comment]
My null-safe branch can now be merged, as i fixed the last bit of cast error and can confirm that all tests are passing.

**Pull request merged**
